#pragma once

#include <SDL2/SDL.h>
#include <SDL2/SDL_image.h>
#include <SDL2/SDL_mixer.h>
#include <SDL2/SDL_ttf.h>
#include <chrono>
#include <thread>
#include <cmath>
#include <memory>
#include <array>
#include <map>
#include <deque>
#include <list>
#include <stdio.h>
#include <fstream>
#include <vector>
#include <string>
#include <rapidjson/document.h>
#include <iostream>
#include "vector2.hpp"
#include "renderwindow.hpp"
#include "sprite.hpp"
#include "sound.hpp"
#include "level.hpp"
#include "player.hpp"
